"""renamed verified to confirmed

Revision ID: 1709724f096a
Revises: fa3f5e8e3e74
Create Date: 2022-05-18 20:43:06.131845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1709724f096a'
down_revision = 'fa3f5e8e3e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
