"""empty message

Revision ID: 83287a4f9e99
Revises: d20ae7e08d59
Create Date: 2022-05-22 17:54:39.064242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83287a4f9e99'
down_revision = 'd20ae7e08d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stocks.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_table('stock_prices')
    # ### end Alembic commands ###
