"""empty message

Revision ID: c134941c16a7
Revises: 83287a4f9e99
Create Date: 2023-03-15 21:16:16.330315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c134941c16a7'
down_revision = '83287a4f9e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'last_updated')
    # ### end Alembic commands ###
