"""empty message

Revision ID: e0dc454394f4
Revises: 00d85a6c081d
Create Date: 2024-04-17 03:15:28.268652

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e0dc454394f4"
down_revision = "00d85a6c081d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_prices", schema=None) as batch_op:
        batch_op.alter_column(
            "volume",
            existing_type=sa.FLOAT(),
            type_=sa.Integer(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_prices", schema=None) as batch_op:
        batch_op.alter_column(
            "volume",
            existing_type=sa.Integer(),
            type_=sa.FLOAT(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
