# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Cadams CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.0"
        architecture: "x64"
      env:
        AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

    - name: Install dependencies
      run: |
        python -m pip install pip==22.0.4
        pip install pip-tools
        make pip
        python -m nltk.downloader brown
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        make lint
        
    - name: Test with pytest
      run: |
        coverage run --source app/ -m pytest tests/

    - name: Coverage Report
      run: |
        coverage report
